### ISSUE TITLE
JS context.df.continueAsNew not working in 1.8.0

### ISSUE THREAD

**Issue by deman4ik** [Azure/azure-functions-durable-js#57] opened 2019-03-25 16:13 UTC
**Describe the bug**
contunueAsNew stopped working after updating to 1.8.0
in 1.7.1 it works fine

**Investigative information**

- Durable Functions extension version: 1.8.0
- Function App version (1.0 or 2.0): 2.0
- Programming language used: JS
- durable-functions npm module version: 1.1.4

**To Reproduce**
https://github.com/deman4ik/funcs-durable-js

- func extensions install
- npm install
- func start

1. POST http://localhost:7071/api/HttpTrigger with any not null data in body
2. Check HubHistory

**Expected behavior**
Orchestrator started with random not null input
Checks Input
continueAsNew with new state (false)
Orchestrator started with "false" input
Checks Input
Orchestrator finished with result "false"

**Actual behavior**
Orchestrator started with random not null input
Checks Input
Orchestrator finished with result from input

**Comment by kashimiz** [comment] 2019-03-25 23:01
Thanks for reporting this issue, @deman4ik , and for including a repro! It looks like the npm library is returning the expected execution payload, but the extension isn't consuming it properly. I'll investigate this one further.

**Comment by deman4ik** [comment] 2019-04-01 11:09
Any ETA? We need some features from 1.8.0

**Comment by kashimiz** [comment] 2019-04-01 21:24
My apologies for the delay in response @deman4ik. It looks like this regression is a result of this [bugfix](https://github.com/Azure/azure-functions-durable-extension/commit/e43843d713de9884f5e08d5cda9fbfd9a62795b0). I don't have an ETA on a fix just yet but will keep this thread updated.

**Comment by Eikc** [comment] 2019-04-05 19:06
Is there any workaround for making the durable functions work with continueAsNew until there is a fix ?

**Comment by deman4ik** [comment] 2019-04-05 19:09
@Eikc We just downgraded to 1.7.1 Durable Functions extension version

**Comment by Eikc** [comment] 2019-04-05 19:10
@deman4ik Do you still use the 1.1.4 version of the durable-functions package ? Or does that need to be downgraded as well?

**Comment by deman4ik** [comment] 2019-04-05 19:11
@Eikc yep still 1.1.4 npm package

**Comment by Eikc** [comment] 2019-05-05 17:53
Hey @kashimiz 

I hate to ask, but is there any news on this issue? or anyway that I or others can help with this great package? I really need to get up on Durable 1.8.1 and this is sadly blocking me from using it..

Anyway, I would love to help. I just need a pointer in the right direction getting started :)

**Comment by kashimiz** [comment] 2019-05-07 00:44
(@Eikc and @deman4ik for FYI) This issue has been fixed as of the v1.8.1 release of the Durable Functions extension, which went out on 5/4. It's supported by v1.2.0 durable-functions npm package.

Closing this for now, but please reopen if your issue persists with the new releases.

**Comment by Eikc** [comment] 2019-05-09 14:14
@kashimiz I don't think it works properly..

If you take the example from https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-eternal-orchestrations

then i receive a `Exception: TypeError: Cannot convert undefined or null to object` and it might be related to #61 

If i try to do something different like returning or yielding the context.df.continueAsNew, it just stops but within the table storage it's status is still "running".. No further events are added to the table and the instanceId is not being reset with a new executionId as stated in the docs

```
  context.log('sleeping');
  yield context.df.callActivity("sleep");
  context.log('done sleeping')

  return context.df.continueAsNew(undefined); 
```

I would love to help if I can, since I really would love to use durable functions within our projects :-)

**Comment by waiwaizp** [comment] 2019-05-16 07:39
I think 1.8.1 haven't fixed this issue

**Comment by kepikoi** [comment] 2019-09-25 09:36
Hi. 1.8.3 still hasn't provided a bugfix. I added a repro here https://github.com/kepikoi/azure-functions-durable-js-57-repro

**Comment by nbering** [comment] 2019-09-29 00:32
My case is pretty similar to @kepikoi's reproduction example. I added this after the timer to confirm it was executing the coke after resuming:

```js
context.log("Woke from timer.")
```

It did indeed log, but it doesn't re-schedule itself... effectively halting the eternal orchestration "loop". Downgrading to extension version 1.7.1 didn't seem to affect anything. 

I tried to trace down further just by following dependencies on GitHub, to see what the continueAsNew function actually does... but I couldn't find any implementation beneath simple interface definition. As far as I can tell, the JS function is being called, but it just has no effect.

**Comment by leo-buneev** [comment] 2019-10-08 09:40
Can confirm, continueAsNew doesn't work neither in extension v1.8.3 nor in extension v2.0.0-beta2.
Downgrading extension to v1.7.* solves this particular issue, but there are other issues present in older extension version

**Comment by cgillum** [comment] 2019-10-08 20:28
@ConnorMcMahon could you look at this when you get a chance? This issue has been open for a while and I suspect our out-of-proc logic may not be handling `continueAsNew` correctly.

**Closed** 2019-11-01 00:05 UTC
Labels: bug, fix-ready

**Comment by nbering** [comment] 2019-11-24 05:05
1.3.1 release still didn't fix my issue, running with the example from the docs.

But I found that if I `yield` for the continueAsNew, like this, it works:
```
yield context.df.continueAsNew(undefined)
```
Code is TypeScript 3.6.3 if that makes any difference.

Without the yield, the orchestrator just finishes and never re-schedules itself.

**Comment by ConnorMcMahon** [comment] 2019-11-25 20:09
Thanks for the update @nbering. In my fix for this issue, I tested the `yield` and `return` case. I will open a new issue for the case you mentioned.

**Comment by nbering** [comment] 2019-11-26 01:34
@ConnorMcMahon Here's the sample for Eternal Orchestrators from the docs site:

```js
const df = require("durable-functions");
const moment = require("moment");

module.exports = df.orchestrator(function*(context) {
    yield context.df.callActivity("DoCleanup");

    // sleep for one hour between cleanups
    const nextCleanup = moment.utc(context.df.currentUtcDateTime).add(1, "h");
    yield context.df.createTimer(nextCleanup.toDate());

    context.df.continueAsNew(undefined);
});
```
https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-eternal-orchestrations

If this was supposed to have a return, then that's what tripped me up.

**Comment by ConnorMcMahon** [comment] 2019-11-26 16:49
@nbering 
I believe that example is perfectly reasonable. I just tested against an example that used `return`/`yield`, so I didn't entirely fix this case. I have opened #126 to track fixing that specific issue.
