### ISSUE TITLE
extendedSessionsEnabled causes the orchestration to hang in pending/running state

### ISSUE THREAD

**Issue by Khadgar** [Azure/azure-functions-durable-js#214] opened 2020-08-12 19:27 UTC
**Describe the bug**
Adding `extendedSessionsEnabled` [configuration](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#extended-sessions) to `host.json` causes the orchestration to be stuck in pending / running state.

**Investigative information**

- Durable Functions extension version: **2.2.2**
- durable-functions npm module version: **1.4.3**
- Language (JavaScript/TypeScript) and version: **Typescript 3.9.5**
- Node.js version: **v10.14.1**

***If deployed to Azure App Service***

- Timeframe issue observed: ***08/12/2020 11:00 AM - 08/12/2020 11:30AM PDT***
- Function App name: **empowermddatastorage-test2**
- Function name(s): **invocationId d41e096d-e0a6-4035-bfca-cb9ef929d257**
- Region: **West US 2**

**To Reproduce**
1. Create a function app in portal with node runtime
2. Use the following `host.json` 
3. Start the orchestration
```
{
    "version": "2.0",
    "functionTimeout": "00:10:00",
    "extensions": {
        "durableTask": {
            "maxConcurrentActivityFunctions": 4,
            "extendedSessionsEnabled": true,
            "extendedSessionIdleTimeoutInSeconds": 60
        }
    }
}
```

**Expected behavior**
Extended sessions should work how it described in the [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#extended-sessions)

**Actual behavior**
After executing the orchestrator function it is hanging in pending / running state with no request.

**Known workarounds**
 Removing the `extendedSessionsEnabled` fixes the issue of being stuck in pending / running state.

**Comment by davidmrdavid** [comment] 2020-08-14 17:02
Hi @Khadgar ,

Thank you for reaching out. As you pointed out, this is a duplicate / a consequence of the issue already described here: https://github.com/Azure/azure-functions-durable-js/issues/98

We're certainly looking into enabling this in some future, but the feature is not available in JS at the moment. We'll update our docs to make sure this is communicated. As soon as we enable this feature, we'll update issue #98 :) .

If you feel like this issue is not a duplicate of #98, then please let us know. In the meantime, I'll close this issue as a duplicate.

Thanks for reaching out!

⚡ ⚡

**Closed by davidmrdavid** 2020-08-14 17:02 UTC
Labels: Needs: Triage :mag:
