### ISSUE TITLE
uuid v3 gives warning on npm install

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-durable-js#316] opened 2022-01-30 00:39 UTC
**Describe the bug**
uuid v3 gives the following warning on npm install.

```
$ npm i durable-functions
npm WARN deprecated uuid@3.3.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

**Comment by lilyjma** [comment] 2024-01-05 23:41
Closing as it's a duplicate of #483

**Closed by lilyjma** 2024-01-05 23:41 UTC
Labels: dependencies
