### ISSUE TITLE
Durable Entity Client Functions don't work with v1 bundles

### ISSUE THREAD

**Issue by ChristianEder** [Azure/azure-functions-durable-js#190] opened 2020-05-21 09:14 UTC
**Describe the bug**
I am trying to create an HTTP-triggered durable entity client function, but cannot get it to work. I tried 2 different approaches:

1) Defining an `durableClient` input binding as stated in the documentation (https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings#entity-client)

This approach leads to my HTTP triggered function not being triggered at all: No logs show up when I get the functions URL, and I get an 404 response.

2) Instead, defining an `orchestrationClient` input binding

This approach leads to the error message "Cannot use the signalEntity API with this version of the Durable Task Extension" showing up in the logs, along with a 500 response code.

**Investigative information**

- Durable Functions extension version:
- durable-functions npm module version: 1.4.1
- Language (JavaScript/TypeScript) and version: JS
- Node.js version:

Contents of my host.json file:

```json
{
  "version": "2.0",
  "tracing": {
    "consoleLevel": "verbose"
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
}
```

function.json file for approach 1):
```json
{
  "disabled": false,
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "name": "client",
      "type": "durableClient",
      "direction": "in"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
```

function.json file for approach 2):
```json
{
  "disabled": false,
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req"
    },
    {
      "name": "client",
      "type": "orchestrationClient",
      "direction": "in"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "$return"
    }
  ]
}
```

***If deployed to Azure App Service***

- Timeframe issue observed: 2020-05-21, ~11:00 CEST
- Function App name: durable6f00398b 
- Function name(s): hello (approach 1) and hello3 (approach 2)
- Region: WestEurope
- Orchestration instance ID(s): didnt get that far

**To Reproduce**

1. Open 'https://durable6f00398b.azurewebsites.net/api/hello' --> receive HTTP 404
2. Open 'https://durable6f00398b.azurewebsites.net/api/hello3' --> receive HTTP 500

**Expected behavior**
My durable client function is able to signal an entity function

**Actual behavior**
My durable client function is either not triggered at all (approach 1) or unable to signal an entity (approach 2)

Function invocation id for approach 2: 'd232285c-551e-4987-a5c6-614b89aab987'

**Comment by davidmrdavid** [comment] 2020-06-16 16:54
Hi @ChristianEder ,

I'm very sorry for the late response, we did not see this one. I'll be taking a look in the coming days, so expect an update from me. If you managed to get around the error, please let us know. Thanks!

⚡ ⚡

**Comment by ChristianEder** [comment] 2020-06-17 08:07
Thanks for the update, and no I didn't manage to get around this yet.

**Comment by davidmrdavid** [comment] 2020-06-18 19:07
Hi @ChristianEder, did you develop this locally or on the Azure Portal? Also, if you have a small reproducer `.zip`, I can help you get it running faster.

I believe I know what's causing this error though. To explain it, I first need to establish some context though. 

Durable Functions is a multi-language service with its core backend logic implemented in C# and language specific SDKs to bind that C# logic into, say, JavaScript. Here's [the backend](https://github.com/Azure/azure-functions-durable-extension) and [this very repo](https://github.com/Azure/azure-functions-durable-js) is a language-specific SDK.

Since we do not want JavaScript users to worry about installing and maintaining a C# dependency, the backend, we handle it for you via "extension bundles" which are ready-to-go installations of the durable-extension repository. You specify which version range of the extension bundle to install in `host.json` via this portion:

```JSON
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
```

So, in that snippet above, you are saying that you are accepting extension bundles of version `1.x` up to but not including version `2.x`.

With that in mind, entities is not supported for versions `1.x`, they only supported for `2.x` 😄 

In the very near future, the solution to this will be to update the version range in the `host.json`, but currently we do not have extension bundles available for versions `2.x` of the backend. This means that, if you want to use entities, you'll need to manually update your backend version. 

You can find instructions to do this in the first 3 bullet points of the [Contibutor's Guide](https://github.com/Azure/azure-functions-durable-js/blob/dev/CONTRIBUTING.md#debugging-end-to-end-with-the-durable-extension). In short, the instructions specify that you need to remove the `extensionBundle` portion of your `host.json`, create a `extensions.csproj` file indicating the version of the extension you want to install, and running `func extensions install` on that directory. Again, instructions can be found in the first 3 bullet-points of the contributor's guide linked above. If this doesn't work for you, I'd be happy to help you out further!!

Please let me know if you need more assistance and I'll try my best to get you unstuck. It is also our fault that the docs do not make this clear, and I'm in the process of updating them to improve this situation. Again, once the bundles for v2 release, this should not be a problem, but we are currently in a transition period. Thanks for understanding and let me know if I can be of more help!

⚡ ⚡

**Comment by ChristianEder** [comment] 2020-07-07 09:51
Hi @davidmrdavid - thanks for your response and extensive explanation! Unfortunately, this probably won't help because I don't need to fix this for a specific of my apps, but rather for the Durable Entity support within the [Pulumi NodeJS SDK](https://github.com/pulumi/pulumi-azure/tree/master/sdk/nodejs). I think I'll need to wait until the extension bundle for 2.x is out - where can I get notified / updated on this?

**Comment by davidmrdavid** [comment] 2020-07-08 02:15
Hi @ChristianEder 
I see. Yeah that may be tricky to do. We are currently in the process of releasing extension bundles v2, and it appears like we are about a month from completion. The earliest date we have, internally, is around the 20th of July, but that's subject to being slightly delayed somewhat. Do you mind checking back at around that time for an update on the release? I'm sorry for the inconvenience 😞

**Comment by ChristianEder** [comment] 2020-07-08 08:57
Will do, thanks!

**Comment by justinmchase** [comment] 2020-08-28 13:07
it was released and I was able to upgrade my host.json like so:
```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  }
}
```

And now the `entityTrigger` type works

**Comment by davidmrdavid** [comment] 2020-08-28 15:46
Great to hear! And indeed, that's the intended usage. I'll close this issue, for now, as it appears resolved. Please let us know if the issue persists and we'll re-open. Hope y'all enjoy entities in JS :)

**Closed by davidmrdavid** 2020-08-28 15:46 UTC
Labels: Needs: Triage :mag:
