### ISSUE TITLE
An activity function that returns false is converted to null in orchestrator

### ISSUE THREAD

**Issue by sdoucetOctopus** [Azure/azure-functions-durable-js#50] opened 2019-02-15 18:44 UTC
Hi,

I'm using v1.1.4 of durable-functions in javascript.

I have an activty function that returns whether a condition is met, let's say it's :
```
module.exports = async function (context) {
    return false;
};
```

When my orchestrator calls this activity funciton, it receives null instead of false :
```
module.exports = df.orchestrator(function* (context) {
    const myState = yield context.df.callActivity('myActivity');
    return `My state is ${myState}`;
});
```

If my activity function returns true instead of false, the result is correct, indeed true.
Am I missing something here or it's a bug ?

Thanks

**Comment by kashimiz** [comment] 2019-06-05 21:34
Repro'd this. Also occurs for `0`, `''`/`""`, and `NaN`.

**Comment by kashimiz** [comment] 2019-06-06 23:46
This has been partially fixed; when returning `undefined` or `NaN`, which have no equivalent in the underlying .NET extension, the orchestrator's output still appears as `null`.

**Comment by anthonychu** [comment] 2020-01-09 17:59
I think `undefined` and `NaN` could be difficult to support. Suggest closing this issue and adding a new one to document valid return types. @ConnorMcMahon what do you think?

**Comment by ConnorMcMahon** [comment] 2020-01-09 18:08
We could theoretically encode it in a specific way, but I'm not sure it is worth the effort for now. I think documenting it is the right approach, and we only invest the effort if there is demand for it.

**Comment by Mirco469** [comment] 2020-12-17 11:34
Hi, i think the problem is not solved for return value false.
I'm using durable-functions v. 1.4.4 for javascript and when i return true from my activity function everything works fine. However when my activity function returns false my orchestrator function receives null.
I'm running the code on Azure.

**Comment by davidmrdavid** [comment] 2020-12-17 19:31
To my surprise, I am too seeing this problem @Mirco469. I'll investigate this shortly

**Comment by davidmrdavid** [comment] 2020-12-23 00:32
I think something changed at the `azure-functions-nodejs-worker` level because `durable-extension`, which is the engine that powers `azure-functions-durable-js` is also receiving `null` as the output of the activity, so the nodejs worker must be failing to serialize it.

This is the line in `durable-extension` where I would expect to receive `false` as the value of `serializedOutput`:
https://github.com/Azure/azure-functions-nodejs-worker

Unfortunately, with the holidays coming up and my team-members from that team likely out of office, this might take a little bit to fix. In the meantime, returning a string should allow us to at least mitigate this issue without losing functionality.

I'll look to submitting a patch as soon as my `nodejs-worker` team-members are back from their holiday break! ⚡ ⚡

**Comment by hossam-nasr** [comment] 2022-06-30 22:14
@davidmrdavid has this been fixed by https://github.com/Azure/azure-functions-nodejs-worker/pull/383? Can we close this issue?

**Comment by davidmrdavid** [comment] 2022-07-05 18:10
Yup, thanks for the triage, @hossam-nasr!

**Closed by davidmrdavid** 2022-07-05 18:10 UTC
Labels: bug
