### ISSUE TITLE
[JS] yielding the same callActivity task twice (as follow-up to df.Task.any()) results in activity being incorrectly triggered twice

### ISSUE THREAD

**Issue by cliffkoh** [Azure/azure-functions-durable-js#85] opened 2019-05-30 17:00 UTC
In the code below, the activity corresponding to checkActivity fires twice. According to @cgillum, this does not happen with the C# version and should not happen per-design and represents a bug in the JS library.

Note: This bug blocks "Listen for external event whilst waiting for activity, then resuming the wait for that activity pattern"

```ts
const checkActivity = context.df.callActivity(...);
const listenForEvent = context.df.listenForExternalEvent(...);
const taskArray = [checkActivity, listenForEvent];
 
const winner = yield context.df.Task.any(taskArray);
  
 if(winner === listenForEvent) {
   yield checkActivity;
 }else{
   // ...
 }

```

**Comment by kashimiz** [comment] 2019-06-07 00:32
Hi @cliffkoh, thanks for reporting this issue. Can you confirm the following information so I can investigate?

* Durable Functions extension version:
* durable-functions npm module version:

**Comment by ConnorMcMahon** [comment] 2019-10-31 23:49
Found the root cause of this, but won't make it into 1.3.1. Will make it into 1.3.2.

**Comment by cgillum** [comment] 2020-01-09 02:12
v1.3.2 is released. Closing this issue.

**Closed by cgillum** 2020-01-09 02:12 UTC
Labels: bug
