### ISSUE TITLE
The host name of createCheckStatusResponse() result is "localhost"

### ISSUE THREAD

**Issue by yoichiro** [Azure/azure-functions-durable-js#77] opened 2019-05-08 10:25 UTC
## Abstract

After starting an orchestrator with the `client.startNew(...)` calling, we can call the `client.createCheckStatusResponse()` function and can retrieve a URL list as the call result. But, the host names of all URLs are `localhost`.

## Expected Behavior

These host names should be valid host names. At least, in the C# environment, we can get a valid host name.

## Actual Behavior

These host names of the URLs included into the result of `createCheckStatusResponse()` calling are `localhost` at all times.

## How to Reproduce This Issue

For example, you can get the URL list by the following code:

```
const df = require('durable-functions');
module.exports = async function(context, req) {
  const client = df.getClient(context);
  const instanceId = await client.startNew("OrchestrationFunction", undefined, undefined);
  const checkStatusResponse = client.createCheckStatusResponse(req, instanceId);
  context.log(checkStatusResponse);
  ...
};
```

Then, you should get like the following log:

```
{ status: 202,
  body: 
   { id: '904672609e7540dbb060844306aa5395',
     statusQueryGetUri: 'https://localhost/runtime/webhooks/durabletask/instances/<INSTANCE_ID>?taskHub=DurableFunctionsHub&connection=Storage&code=<CODE>',
     sendEventPostUri: 'https://localhost/runtime/webhooks/durabletask/instances/<INSTANCE_ID>/raiseEvent/{eventName}?taskHub=DurableFunctionsHub&connection=Storage&code=<CODE>',
...
```

As you see above, all `***Uri` has the `localhost` host name.

**Comment by yoichiro** [comment] 2019-05-08 20:55
@kashimiz Thank you for the comment.

> What environment are you experiencing this in - are you running locally or in Azure? 

I tested my code in Azure and I got these responses which has such URL including `localhost`.

>  In either environment, what is the value of process.env.WEBSITE_HOSTNAME within your app?

When I wrote the code including the following code for debug:

```
context.log('process.env.WEBSITE_HOSTNAME', process.env.WEBSITE_HOSTNAME);
```

Then, I deployed the code to Azure and executed the code, I got the following log:

```
2019-05-08T20:51:47.349 [Information] process.env.WEBSITE_HOSTNAME yoichiro-df1.azurewebsites.net
```

It seems that the result host name is valid, that is, it was actually the host name which is the target I deployed.

**Comment by yoichiro** [comment] 2019-05-09 01:18
@kashimiz I investigated the reason of this issue. For instance, I investigated the behavior of the `private getClientResponseLinks()` method of the `DurableOrchestrationClient` class.

For example, when the loop handles the `statusQueryGetUri` URL in the method, I got the following values:

**Current getClientResponseLinks() Code**

```js
private getClientResponseLinks(request: IHttpRequest | HttpRequest, instanceId: string): HttpManagementPayload {
    const payload = { ...this.clientData.managementUrls };

    (Object.keys(payload) as Array<(keyof HttpManagementPayload)>).forEach((key) => {
        if (this.hasValidRequestUrl(request) && isURL(payload[key], this.urlValidationOptions)) {
            const requestUrl = new url.URL((request as HttpRequest).url || (request as IHttpRequest).http.url);
            const dataUrl = new url.URL(payload[key]);
            payload[key] = payload[key].replace(dataUrl.origin, requestUrl.origin);
        }

        payload[key] = payload[key].replace(this.clientData.managementUrls.id, instanceId);
    });

    return payload;
}
```

**Actual values at handling "statusQueryGetUri"**

```
2019-05-09T00:21:54.352 [Information] *** key: statusQueryGetUri
2019-05-09T00:21:54.352 [Information] *** hasValidRequestUrl(): true
2019-05-09T00:21:54.353 [Information] *** isURL(): true
2019-05-09T00:21:54.353 [Information] --- request.url: undefined
2019-05-09T00:21:54.353 [Information] --- request.http.url: https://localhost/api/fulfillment
2019-05-09T00:21:54.353 [Information] --- requestUrl: https://localhost/api/fulfillment
2019-05-09T00:21:54.353 [Information] --- dataUrl: https://yoichiro-df1.azurewebsites.net/runtime/webhooks/durabletask/instances/INSTANCEID?taskHub=DurableFunctionsHub&connection=Storage&code=0VsYyQgfow8PRLf18XN36OLqT4auqbfC5pr5FBNXS0sL9ERUb5SWag==
2019-05-09T00:21:54.354 [Information] --- payload[key] (before replacing origin): https://yoichiro-df1.azurewebsites.net/runtime/webhooks/durabletask/instances/INSTANCEID?taskHub=DurableFunctionsHub&connection=Storage&code=0VsYyQgfow8PRLf18XN36OLqT4auqbfC5pr5FBNXS0sL9ERUb5SWag==
2019-05-09T00:21:54.357 [Information] --- payload[key] (after replacing origin): https://localhost/runtime/webhooks/durabletask/instances/INSTANCEID?taskHub=DurableFunctionsHub&connection=Storage&code=0VsYyQgfow8PRLf18XN36OLqT4auqbfC5pr5FBNXS0sL9ERUb5SWag==
```

That is, we already had the URL which has the valid origin name `https://yoichiro-df1.azurewebsites.net`, however, the `statusQueryGetUri()` method code replaced the origin into the `localhost` using the `request.http.uri` value.

I can't find any reason why the replacing process was necessary. I guess that this issue will be fixed by removing the replacing logic or by changing the logic to replace the origin with the `process.env.WEBSITE_HOSTNAME` value or one of the `client.uniqueWebhookOrigins` values, for example...

**Comment by yoichiro** [comment] 2019-05-17 01:39
@kashimiz I would like to create a pull request to fix this issue. To create that, I need to know the correct way to determine the origin string.

Currently, I know the following facts in case of executing my code deployed to the `yoichiro-df1` function app on Azure (that is, not local environment).

* The `process.env.WEBSITE_HOSTNAME` was `yoichiro-df1.azurewebsites.net`. And, the `request.http.url` was `https://localhost/...` when the concrete function called.
* When the `getClient()` called, the origin of each URL included into the `managementUrls` was `https://yoichiro-df1.azurewebsites.net`.
* If there is no `process.env.WEBSITE_HOSTNAME` or its value includes `0.0.0.0`, the origin of each URL included into the `managementUrls` will be replaced with `http://localhost:7071` by the `getClient()` function.
* The result of the `createCheckStatusResponse()` is actually generated by the `getClientResponseLinks()`. In the function, the origin of each URL included into the `managementUrls` was replaced forcely with the origin of the `request.http.url` value. (`https://yoichiro-df1.azurewebsites.net` -> `http://localhost`)

I think that there are the following ways to fix this issue:

1) Use the original origin string which is included in the `managementUrls` URLs generated by the `getclient()` function without any touches. That is, remove the replacing logic [durableorchestrationclient.ts#L505-L509](https://github.com/Azure/azure-functions-durable-js/blob/dev/src/durableorchestrationclient.ts#L505-L509).

2) Replace the origin string with the `process.env.WEBSITE_HOSTNAME` value. That is, we change the replacing logic [durableorchestrationclient.ts#L506-L508](https://github.com/Azure/azure-functions-durable-js/blob/dev/src/durableorchestrationclient.ts#L506-L508) as the following:

```js
const requestUrl = new url.URL(`https://${process.env.WEBSITE_HOSTNAME}`);
const dataUrl = new url.URL(payload[key]);
payload[key] = payload[key].replace(dataUrl.origin, requestUrl.origin);
```

3) Et cetera.

Which way should I fix this issue from my ideas above?

**Comment by CastleArg** [comment] 2019-07-24 04:47
Hi team, 
Has this been merged?  I am getting the correct hostname in my status object.
However, I cannot actually get the status from these URIs..
I have some azure function proxies - one of which routes everything unknown to my SPA UI to prevent 404s, then I have more specific proxies for api etc.
When I set a proxy for %WEBSITE_HOSTNAM%/runtime/webhooks/durabletask/instances  it dies on an infinite loop.  Do you think this is related or a separate issue?

**Comment by ConnorMcMahon** [comment] 2019-09-11 18:14
@yoichiro ,

What seems to be the actual bug here is that your value for `req.http.url` is using `localhost` instead of the actual hostname of the request. This should not be the case, and might be a bug in the NodeJS language worker.

When I run the same code you posted on my application connor-nodejs, the hostname of `req.http.url` was the expected hostname of "connor-nodejs.azurewebsites.net", and the logic in `createCheckStatuResponse()` worked exactly as expected.

@CastleArg, your issue seem to be separate, and I would create a separate issue with as much details as possible so it is easy for us to reproduce, and investigate whether it is a bug, or expected behavior.

**Closed** 2019-10-30 19:00 UTC
Labels: Needs: Author Feedback, P1, bug, no-recent-activity
