### ISSUE TITLE
Execution stuck in "runTime: Pending" state

### ISSUE THREAD

**Issue by dozienwankwoh** [Azure/azure-functions-durable-js#285] opened 2021-08-30 14:36 UTC
**Describe the bug**
Execution stuck in "runTime: Pending" state

**Investigative information**

- Durable Functions extension version: latest
- durable-functions npm module version: latest
- Language (JavaScript/TypeScript) and version: js
- Node.js version: 14

***If deployed to Azure App Service***

- Timeframe issue observed: "createdTime": "2021-08-30T13:34:41Z"
- Function App name:
- Function name(s):
- Region: South Central US
- Orchestration instance ID(s): b43a5f74d232422abe67707961efb2b0

**To Reproduce**

> While not required, providing your orchestrator's source code in anonymized form is often very helpful when investigating unexpected orchestrator behavior.

**Expected behavior**
Completed function execution

**Actual behavior**
Execution stuck in "runTime: Pending" state

**Known workarounds**
No known workarounds

**Comment by davidmrdavid** [comment] 2021-08-30 16:50
Hi @dozienwankwoh,

Thank you for reaching out! Is this issue reproducible locally? If so, can you please provide us with a local reproducer?
Otherwise, we will need the **full** information below in order to start an investigation:

**Timeframe issue observed:
Function App name:
Function name(s):
Region: South Central US
Orchestration instance ID(s):** 

Thanks!

**Comment by dozienwankwoh** [comment] 2021-08-30 17:14
The issue is not reproducible locally. Full details:

Timeframe issue observed: "createdTime": "2021-08-30T13:34:41Z"
Function App name: gstcelanese-managedb02
Function name(s): OrchestrateSQLQuery
Region: South Central US
Orchestration instance ID(s): b43a5f74d232422abe67707961efb2b0

Also, to add on-- when I watch the logs in the Azure console, I see that the HTTP starter function is invoked but the Orchestrator function's logs do not show that it is invoked. Locally, the starter function invokes the orchestrator just fine.

**Comment by davidmrdavid** [comment] 2021-08-30 17:56
Hi @dozienwankwoh,

Thank you for the prompt response. Looking at our internal logs, it seems you're using extension bundles V1. 

Could you please upgrade to extension bundles V2 in your `host.json`? All it requires is that you change the `version` tag to `[2.*, 3.0.0)`.

Upgrading to the latest extension bundles will make sure you have the latest bug fixes and performance improvements, so the first step to mitigating this issue is almost certainly to upgrade. Please let me know if this is possible, thanks!

**Comment by dozienwankwoh** [comment] 2021-08-30 18:24
Thank you @davidmrdavid I believe you solved my issue! The function is now completing.

Is there a best way to ensure my extension bundles stay up to date?

**Comment by davidmrdavid** [comment] 2021-09-02 17:30
That's great to hear @dozienwankwoh! Broadly speaking, your current setup should pick up the latest extension bundles so long as `v2` is the latest major version of bundles itself.

@anthonychu, is there any guidance on how customers can stay up to date with *major* releases of extension bundles and other related notifications?

**Comment by davidmrdavid** [comment] 2021-09-02 17:30
_I'll also be closing this issue since it seems resolved, but we could still use your input in this thread, @anthonychu _ :)

**Closed by davidmrdavid** 2021-09-02 17:30 UTC
Labels: Needs: Attention :wave:
