### ISSUE TITLE
UTC DateTime type parameter doesn't work for sqlQuery of Cosmos DB bindings

### ISSUE THREAD

**Issue by wisesimpson** [Azure/azure-functions-durable-js#121] opened 2019-11-17 12:37 UTC
**Describe the bug**
I use Node.js and durable functions 2.0.

If I do:
`context.df.callActivity("SampleActivity", {publishDate:"2019-01-31T15:17:30.0000000Z"})`

Then use Cosmos DB input bindings in `SampleActivity`  like below
`sqlQuery: SELECT * FROM c WHERE c.publishDate={publishDate}`

This will return with empty result.
The data is in DB, just something wrong with this sqlQuery.

**Investigative information**

If I change the value of publishDate to non-UTC format like "normal string", then call
`context.df.callActivity("SampleActivity", {publishDate:"normal string"})`

It works fine. So it seems like UTC date type parameter is modified implicitly for sqlQuery in some way. The bug only happens when a string field looks like an UTC date.

This bug might has something to do with another issue I reported:
https://github.com/Azure/Azure-Functions/issues/1399

**Comment by antempus** [comment] 2019-11-18 21:57
You can try and check that the input is being passed in correctly to the `sqlQuery` by comparing the calling source and what the activity receives as the input.

**Comment by wisesimpson** [comment] 2019-11-19 00:06
@antempus Do you know how to check Cosmos DB received activities?

**Comment by ConnorMcMahon** [comment] 2019-11-19 20:07
@wisesimpson 

Can you log the value of `publishDate` inside of your activity function? That would help us diagnose if Durable Functions is doing something odd while passing the parameter to the activity function, or if this is something that needs to be fixed on the CosmosDB binding side of things.

**Comment by wisesimpson** [comment] 2019-11-19 23:39
@ConnorMcMahon 
I logged `context.bindingData.data.publishDate` in the activity function. The output is consistent with the input, meaning it's not modified here.

I also tried standard functions (non-durable functions) with simple http trigger and Cosmos DB output binding. It works find meaning the issue is unlikely on the binding side.

So my guess is that "some weird things" happened while passing `context.bindingData.data.publishDate` to the Cosmos DB binding, something related to UTC format processing.

**Comment by antempus** [comment] 2019-12-01 06:04
@wisesimpson 
When you pass in the object to the activity like this:
`context.df.callActivity("SampleActivity", {publishDate:"2019-01-31T15:17:30.0000000Z"})`
and then use the `sqlQuery` binding options like this:
`sqlQuery: SELECT * FROM c WHERE c.publishDate={publishDate}`

The input is being passed like so: 
`SELECT * FROM c WHERE c.publishDate= {publishDate:"2019-01-31T15:17:30.0000000Z"}`

Is that the intended behavior? I ask because I was trying to use multiple properties of an input in a similar way that doesn't, but it may serve to try passing in the string literal as the input rather than a key/value object as I know that will work for calling activities.

**Comment by wisesimpson** [comment] 2019-12-02 14:58
@antempus Thanks for your reply.
There's problem with this assumption:
> The input is being passed like so:
`SELECT * FROM c WHERE c.publishDate= {publishDate:"2019-01-31T15:17:30.0000000Z"}`

Because `publishDate` isn't the name of activityTrigger. Instead it's just a key of the input object. This is related to how to pass multiple params to an activity function. Let me explain:

[Node.js] Two ways to pass param(s) into an activity function
-
1. A string, works for single param
Imagining the activity trigger is defined like below
    ```
    {
        "name": "activityParam",
        "type": "activityTrigger",
        "direction": "in"
    }
    ```
    If we call it this way `context.df.callActivity("SampleActivity", "param value")`, in Cosmos DB input binding you can use it like `"sqlQuery": "SELECT * FROM c WHERE c.sampleParam= {activityParam}"`.
2. An object, works for multiple params
Imaging the same trigger definition
    ```
    {
        "name": "activityParam",
        "type": "activityTrigger",
        "direction": "in"
    }
    ```
    Then we call it like `context.df.callActivity("SampleActivity", {param1: "value1", param2: "value2"})`. 

    **Things become fuzzy here.**
    What we input is an object, we can retrieve it inside the activity (index.js) like `context.bindings.activityParam`, naturally we can use `context.bindings.activityParam.param1` and `context.bindings.activityParam.param2`. What if I want to use it in Cosmos DB input binding? Before checking any documentation I felt this should work: `"sqlQuery": "SELECT * FROM c WHERE c.sampleParam= {activityParam.param1}"`.

    **It does NOT work**, because `sqlQuery` doesn't support dot notation (for a reason). What you wrote in-between `{}` has to be one param name, no exception on the runtime.

    But I really want to use Cosmos DB binding instead of writing client code and managing connection by myself. I found out if I directly call `{param1}` it works. Something like `"sqlQuery": "SELECT * FROM c WHERE c.sampleParam= {param1} AND c.anotherParam= {param2}"`

    So far, the multiple params input is achieved. There's one thing looks weird to me - the name of activityTrigger ("activityParam") becomes irrelevant here. You can name it whatever but in the Cosmos DB binding you just use the param name of the input object. So the assumption I mentioned in the beginning is incorrect because `publishDate` is not a name of activityTrigger but a param name of the input. Then it should be passed like:
    `SELECT * FROM c WHERE c.publishDate= "2019-01-31T15:17:30.0000000Z"`

As I tested, how you pass the input has nothing to do with the UTC DateTime bug
-
I tested with 2 methods I mentioned above. The bug looks the same. Here's the detail of my test.

Imaging I have a sample entry in Cosmos DB:
```
{
    "title": "2010-01-01T00:00:0"
}
```
Then call the activity function like `context.df.callActivity("SampleActivity", {title: "2010-01-01T00:00:0"})`
In Cosmos DB binding
`"sqlQuery": "SELECT * FROM c WHERE c.title = {title}"`

The sample data can be retrieved successfully. Everything works smoothly. Calling the activity with a string input also works.

**Please pay attention, the sample title is "2010-01-01T00:00:0". There's one zero missing in the end comparing to UTC DateTime format.** If I add one zero to the end, things start to fail. Here's what I mean:

If I update the sample entry to:
```
{
    "title": "2010-01-01T00:00:00"
}
```
Then call the activity function like `context.df.callActivity("SampleActivity", {title: "2010-01-01T00:00:00"})`
The result is empty. The sample data can't be retrieved any more.

So my best guess is: when the input string looks like a date format, somehow the input is modified and then passed to the Cosmos DB binding.

This bug has bigger impact than just equation (=). Newer or older than a time doesn't work neither, like `"sqlQuery": "SELECT * FROM c WHERE c.publishDate > {publishDate}"`. Could we prioritised it a little higher please?

**Comment by antempus** [comment] 2019-12-05 06:51
> **Things become fuzzy here.**
What we input is an object, we can retrieve it inside the activity (index.js) like context.bindings.activityParam, naturally we can use context.bindings.activityParam.param1 and context.bindings.activityParam.param2. What if I want to use it in Cosmos DB input binding? Before checking any documentation I felt this should work: "sqlQuery": "SELECT * FROM c WHERE c.sampleParam= {activityParam.param1}".
**It does NOT work**, because sqlQuery doesn't support dot notation (for a reason). What you wrote in-between {} has to be one param name, no exception on the runtime.
But I really want to use Cosmos DB binding instead of writing client code and managing connection by myself. I found out if I directly call {param1} it works. Something like "sqlQuery": "SELECT * FROM c WHERE c.sampleParam= {param1} AND c.anotherParam= {param2}"

If that does indeed work, there is a definite need to clear up the documentation for this usage; I was trying to get that to work via the dot express on the input to the activity and that wasn't an option; if we can indeed pass an arbitrary number of arguments and access them as if they were additional parameters in the `function.json` expressions for `sqlQuery`, the activity trigger definition is less valuable.

**Comment by lilyjma** [comment] 2022-07-19 22:46
Hi @antempus - apologies for the delayed response. Are you still experiencing this problem by any chance?

**Comment by antempus** [comment] 2022-07-19 22:49
@lilyjma 

It's been a while and it will be a be a while to repro this issue

**Comment by wisesimpson** [comment] 2022-07-20 01:09
It has been too long. I don’t have the context to test it anymore.

**Comment by lilyjma** [comment] 2022-09-20 19:30
@davidmrdavid - maybe we can close this issue?

**Comment by davidmrdavid** [comment] 2022-09-22 17:21
Yep, will close until a repro is available.

**Closed by davidmrdavid** 2022-09-22 17:21 UTC
Labels: breaking-change
