### ISSUE TITLE
Durable Entity recording two invocations after single signal

### ISSUE THREAD

**Issue by spiffytech** [Azure/azure-functions-durable-js#222] opened 2020-11-02 18:50 UTC
**Describe the bug**
I have a Function App where a timer-driven function signals a Durable Entity. Every time the Durable Entity runs I see logs/metrics indicating there are actually two invocations associated with it. One with the expected ~400ms second duration, and another with a ~5ms duration.

If the Entity sends a signal to itself, each signal also causes two invocations.

It does not appear that my Entity handler function is actually being called twice; I do not see doubled log messages if I add `context.log()` calls inside the Entity's handler.

I see this happening both when running my Function App locally with `func host start`, and in the live version of my app deployed to Azure.

I'm mostly concerned about this because it seems like it'd double the invocations I'm billed for, and it makes it hard to find signal in the Function App's logs. I looked for documentation covering this behavior, but was unable to find any.

**Investigative information**

- Durable Functions extension version: `[2.*, 3.0.0)`
- durable-functions npm module version: 1.4.4
- Language (JavaScript/TypeScript) and version: TypeScript 3.9.7
- Node.js version: 12.19.0

***If deployed to Azure App Service***

- Timeframe issue observed: Nov. 1 21:00 EST - Nov. 2 12:00 EST
- Function App name: spiffytech-rss-alerter
- Function name(s): AlerterEntity
- Region: US East
- Orchestration instance ID(s): `@AlerterEntity@main`
Invocation ID: bee4a2c1-b805-4963-8a51-6dd35502b494

**To Reproduce**
1. Clone down [my git repository](https://github.com/spiffytech/rss-alerter/tree/86587bd041bd904186539c983e7a1bf8de68c563/functions)
2. Update local.settings.json to include two values:
  - RSS: any valid RSS feed URL, such as https://news.ycombinator.com/rss
  - WEBHOOK: Any URL, such as https://example.com
3. Start the Function App locally, wait 30 seconds for the timer to trigger, and watch the logs

**Expected behavior**
I expect to see the `TimerTrigger` Function execute, and then the `AlerterEntity` Function to execute just once afterward (per timer interval).

**Actual behavior**

The logs show two `completed` messages and two `Executing`/`Executed` message pairs for the Entity.

```
[2020-11-02T18:37:33.331] Host initialized (434ms)
[2020-11-02T18:37:33.337] Starting task hub worker. InstanceId: . Function: . HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.2.2. SequenceNumber: 1.

Functions:

        AlerterEntity: entityTrigger

        TimerTrigger: timerTrigger

[2020-11-02T18:37:33.424] Worker process started and initialized.
[2020-11-02T18:37:33.439] The next 5 occurrences of the 'TimerTrigger' schedule (Cron: '0,30 * * * * *') will be:
[2020-11-02T18:37:33.439] 11/02/2020 13:38:00-05:00 (11/02/2020 18:38:00Z)
[2020-11-02T18:37:33.439] 11/02/2020 13:38:30-05:00 (11/02/2020 18:38:30Z)
[2020-11-02T18:37:33.439] 11/02/2020 13:39:00-05:00 (11/02/2020 18:39:00Z)
[2020-11-02T18:37:33.440] 11/02/2020 13:39:30-05:00 (11/02/2020 18:39:30Z)
[2020-11-02T18:37:33.440] 11/02/2020 13:40:00-05:00 (11/02/2020 18:40:00Z)
[2020-11-02T18:37:33.440] 
[2020-11-02T18:37:34.215] Task hub worker started. Latency: 00:00:00.8783200. InstanceId: . Function: . HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.2.2. SequenceNumber: 2.
[2020-11-02T18:37:34.218] Host started (1328ms)
[2020-11-02T18:37:34.218] Job host started
Hosting environment: Production
Content root path: /home/spiffytech/Documents/programs/rss-alerter/functions
Now listening on: http://0.0.0.0:7071
Application started. Press Ctrl+C to shut down.
[2020-11-02T18:37:39.285] Host lock lease acquired by instance ID '000000000000000000000000662D6571'.
[2020-11-02T18:38:00.033] Executing 'Functions.TimerTrigger' (Reason='Timer fired at 2020-11-02T13:38:00.0061808-05:00', Id=f5bfe0c9-f4a2-418b-997d-bec73724b7eb)
[2020-11-02T18:38:00.204] @alerterentity@main: Function 'alerterentity (Entity)' scheduled. Reason: EntitySignal:. IsReplay: False. State: Scheduled. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.2.2. SequenceNumber: 3.
[2020-11-02T18:38:00.235] Executed 'Functions.TimerTrigger' (Succeeded, Id=f5bfe0c9-f4a2-418b-997d-bec73724b7eb, Duration=221ms)
[2020-11-02T18:38:00.359] Executing 'Functions.AlerterEntity' (Reason='(null)', Id=9f790491-5d0a-4918-968e-dc012942a006)
[2020-11-02T18:38:00.751] @alerterentity@main: Function 'alerterentity (Entity)' completed '' operation 78c74c5c-9b95-4675-a1fa-8fd8b26a4e9d in 367ms. IsReplay: False. Input: (null). Output: (null). HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.2.2. SequenceNumber: 4.
[2020-11-02T18:38:00.757] @alerterentity@main: Function 'alerterentity (Entity)' started. IsReplay: False. Input: (1072 bytes). State: Started. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.2.2. SequenceNumber: 5.
[2020-11-02T18:38:00.766] @alerterentity@main: Function 'alerterentity (Entity)' completed. ContinuedAsNew: True. IsReplay: False. Output: (244 bytes). State: Completed. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.2.2. SequenceNumber: 6.
[2020-11-02T18:38:00.773] Executed 'Functions.AlerterEntity' (Succeeded, Id=9f790491-5d0a-4918-968e-dc012942a006, Duration=416ms)
[2020-11-02T18:38:00.800] Executing 'Functions.AlerterEntity' (Reason='(null)', Id=872a2731-7d7c-4a84-a535-9f4e2d84d8d6)
[2020-11-02T18:38:00.805] Executed 'Functions.AlerterEntity' (Succeeded, Id=872a2731-7d7c-4a84-a535-9f4e2d84d8d6, Duration=4ms)
^CApplication is shutting down...
```

Application Insights also shows a consistent double execution with the same tick-tock pattern of execution durations:
![Application Insights](https://user-images.githubusercontent.com/77867/97906226-4db09600-1d11-11eb-9e68-e7616ecffec4.png)

**Additional context**

- Development environment: VS Code 1.50.1, Linux
- Function Tools: 3.0.2931-1, Linux/Ubuntu 20.04
- Links to source: [Github](https://github.com/spiffytech/rss-alerter/tree/86587bd041bd904186539c983e7a1bf8de68c563/functions)
- Additional bindings used
- Function invocation IDs: bee4a2c1-b805-4963-8a51-6dd35502b494

**Comment by davidmrdavid** [comment] 2020-11-17 02:49
Hi @spiffytech, 

Sorry for the late acknowledgement of this ticket, somehow I missed it. I'll take a look at this tomorrow morning. Just double-checking, in the meantime: this problem is still ongoing, correct?

**Comment by spiffytech** [comment] 2020-11-17 17:47
Yep, I'm still seeing the ticktock pattern of two Function invocations per timer call, one very brief and one with the expected duration.

![Function monitor activity](https://user-images.githubusercontent.com/77867/99427068-eda21e00-28d2-11eb-92c7-43fb6ca4764c.png)

**Comment by davidmrdavid** [comment] 2020-11-19 21:17
Hi @spiffytech , just confirming that I can reproduce this behavior. I also stepped through the execution of the Durable Functions JavaScript SDK and realized that, on the second (and smaller) entity execution, the work item batch of the entity is empty so it in fact does no work.

I've recently been developing Entities for Durable Functions Python and this behavior looks familiar to me. When developing the SDK for Python, I believe to have also experienced these "work-less" executions of Entities. I'm not sure if this is due to some replay behavior, or if it is some limitation of the Durable Functions out-of-process model, but I agree it's confusing.

Let me consult with the larger Durable Functions team to get their thoughts on this. I'll get back to you.

**Comment by davidmrdavid** [comment] 2020-11-19 21:42
Another update:
We have seen cases like this before, especially with scheduled signals. When that occurs, we can sometimes "pop" a message for an entity before it's firing time and, when that occurs, we ignore those messages and re-schedule them for later. I _wonder_ if you're seeing something like this with the TimerTriggere'd function. Obviously, it can't be the same issue, but perhaps it's similar given how frequently you're invoking the entity.

That being said, it would appear that this is happening more frequently in JS and Python (our out-of-process SDKs) so perhaps there's something more immediate we can fix in there. I'll continue investigating. Your sample is _really_ helpful here, so thank you!

**Comment by spiffytech** [comment] 2020-11-19 21:55
I have another Function App with an entity running on a timer that's displaying the same behavior, though that timer only runs every five minutes.

![logs for second Function App](https://user-images.githubusercontent.com/77867/99728695-cf315380-2a87-11eb-950a-04539fc6349e.png)

**Comment by davidmrdavid** [comment] 2020-11-19 21:58
Thanks for confirming. I've taken note of that too.

**Comment by sebastianburckhardt** [comment] 2021-02-04 19:05
I think this is a result of how we implemented entities by using eternal orchestrations in DTFx.

What happens is that every time an entity finishes processing all of its operations, it calls ContinueAsNew.
That means that it actually runs another function invocation to start the orchestration from the top. 

This second invocation will almost always be "empty", i.e. it just starts and then blocks waiting for the next event.

**Comment by davidmrdavid** [comment] 2021-02-17 21:28
That makes a lot of sense, @sebastianburckhardt, thank you.
So that implies these double logs are very much expected, although they're also a tad confusing.

I see two options moving forward.
(1) We could just document this and leave it as-is, and to point any follow-up questions about this matter to that documentation. Ideally we would highlight this in the entity docs as a potential "gotcha"

(2) We could investigate if there are any easy ways to marshal entity execution logs into a single log so we don't have to worry about users, or devs like us, getting tripped-up by this.

Obviously, approach (1) seems easiest but I am curious if (2) is within reach. @ConnorMcMahon, do you know if we have enough control over the logs to avoid this misleading "double entity invocation" record?

**Comment by ConnorMcMahon** [comment] 2021-02-17 21:33
I am hesitant to hide the "duplicate" log from customers, as it may come across as us hiding executions from them. Considering consumption customers pay per execution, that seems potentially problematic.

We should definitely highlight this in our documentation.

**Comment by ConnorMcMahon** [comment] 2021-02-17 21:34
@sebastianburckhardt, it may be worthwhile to see if we can avoid actually invoking the customer's function in our entity middleware for the "empty" invocation. Not sure how possible this would be, but it would be a pretty large win for consumption customers.

**Comment by davidmrdavid** [comment] 2021-02-26 23:15
Closing this ticket since this behavior is now documented here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=csharp#general-concepts

Thanks everyone!

**Closed by davidmrdavid** 2021-02-26 23:15 UTC
Labels: Needs: Triage :mag:
