### ISSUE TITLE
Durable Functions Fail to run 

### ISSUE THREAD

**Issue by pingyin97** [Azure/azure-functions-durable-js#148] opened 2020-01-19 07:58 UTC
I have created a durable function following this document: 
https://docs.microsoft.com/en-us/azure/azure-functions/durable/quickstart-js-vscode

When I run the code and I hit the localhost for my orchestrator i get the following error: 
```
Executed 'Functions.DurableFunctionsHttpStart' (Failed, Id=cb01ef9a-afd8-4489-a54d-ff8cefb1df10)
System.Private.CoreLib: Exception while executing function: Functions.DurableFunctionsHttpStart. System.Private.CoreLib: Result: Failure
Exception: Error: {"Message":"Something went wrong while processing your request","ExceptionMessage":"Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.","ExceptionType":"System.InvalidOperationException","StackTrace":"   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at System.Net.Http.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)\r\n   at System.IO.StreamReader.ReadSpan(Span`1 buffer)\r\n   at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)\r\n   at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)\r\n   at Newtonsoft.Json.JsonTextReader.ParseValue()\r\n   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleStartOrchestratorRequestAsync(HttpRequestMessage request, String functionName, String instanceId) in C:\\GitHub\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 493\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in C:\\GitHub\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 152"}
Stack: Error: {"Message":"Something went wrong while processing your request","ExceptionMessage":"Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.","ExceptionType":"System.InvalidOperationException","StackTrace":"   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at System.Net.Http.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)\r\n   at System.IO.StreamReader.ReadSpan(Span`1 buffer)\r\n   at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)\r\n   at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)\r\n   at Newtonsoft.Json.JsonTextReader.ParseValue()\r\n   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleStartOrchestratorRequestAsync(HttpRequestMessage request, String functionName, String instanceId) in C:\\GitHub\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 493\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in C:\\GitHub\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 152"}
    at DurableOrchestrationClient.<anonymous> (C:\Users\PingFungYin\Desktop\durable\durableJS\node_modules\durable-functions\lib\src\durableorchestrationclient.js:340:43)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\PingFungYin\Desktop\durable\durableJS\node_modules\durable-functions\lib\src\durableorchestrationclient.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5).
```
The code is running on the Azure function app but it isn't running on the localhost

**Comment by cgillum** [comment] 2020-01-20 22:02
This error message points to an incompatibility between the Durable Functions extension and the 3.0 version of the Azure Functions host. if it works in Azure but not in localhost, then there might be some difference between your local and Azure environments.

Some questions:
* What version of the Functions core tools are you running (`func --version`)?
* What version of the Durable Functions extension do you have installed (if you know)?

I suggest you try the following to work around this:

1. Disable [extension bundles](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#extension-bundles) if you are using them. This can be done by deleting the `extensionBundle` field in your **host.json** file.

2. Manually install the latest version of the Durable Functions extension by running this command at the root of your project:

```bash
func extensions install -p Microsoft.Azure.WebJobs.Extensions.DurableTask -v 2.1.1
```

FYI @anthonychu - I'm wondering if this could be a really common issue for folks installing the latest version of the Functions CLI.

**Comment by anthonychu** [comment] 2020-01-20 22:16
Another workaround for now is to set an app setting named `FUNCTIONS_V2_COMPATIBILITY_MODE` to `true`.

I think we need to add the JSON deserialization fix to Durable v1 as well and release an updated extension bundle that includes it.

**Comment by snpdev** [comment] 2020-02-03 16:13
I ran into the same problem in the Microsoft Learn tutorial [Exercise - Create a workflow using Durable Functions](https://docs.microsoft.com/en-us/learn/modules/create-long-running-serverless-workflow-with-durable-functions/4-exercise-create-a-workflow-using-durable-functions).

In the Function app settings blade of my Function resource I see that my Runtime version is ~3, but my `host.json` is:
```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
}
```
To resolve the problem, I set the Runtime version to ~2 and restarted my Function app.

**Comment by manglide** [comment] 2020-02-09 05:37
> I ran into the same problem in the Microsoft Learn tutorial [Exercise - Create a workflow using Durable Functions](https://docs.microsoft.com/en-us/learn/modules/create-long-running-serverless-workflow-with-durable-functions/4-exercise-create-a-workflow-using-durable-functions).
> 
> In the Function app settings blade of my Function resource I see that my Runtime version is ~3, but my `host.json` is:
> 
> ```
> {
>   "version": "2.0",
>   "extensionBundle": {
>     "id": "Microsoft.Azure.Functions.ExtensionBundle",
>     "version": "[1.*, 2.0.0)"
>   }
> }
> ```
> 
> To resolve the problem, I set the Runtime version to ~2 and restarted my Function app.

This helped me. Thanks.

**Comment by anthonychu** [comment] 2020-02-09 07:31
@manglide The `version` property in host.json is a bit confusing, but it's actually the [version of the host.json schema](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#version) and *not* the runtime. Both Azure Functions v2 and v3 use version 2.0 of the host.json schema.

However, the change to `~2` is one way to resolve the problem in this tutorial until the fix is released. The progress of the fix can be tracked here: https://github.com/Azure/azure-functions-durable-extension/issues/1178

FYI @adrianstevens it'll take at least a couple of weeks to get an updated bundle that fixes this issue. Might be worth updating the Learn module to set the runtime to v2 or use the compat mode.

**Comment by GuSuku** [comment] 2020-02-09 14:20
As @anthonychu hinted, adding the following to my `${WORKSPACE_DIR}/local.setting.json` file fixed it for now:

```
{
  "IsEncrypted": ...,
  "Values": {
    ...
    "FUNCTIONS_V2_COMPATIBILITY_MODE": "true"
  }
}
```

**Comment by manglide** [comment] 2020-02-09 16:24
> @manglide The `version` property in host.json is a bit confusing, but it's actually the [version of the host.json schema](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#version) and _not_ the runtime. Both Azure Functions v2 and v3 use version 2.0 of the host.json schema.
> 
> However, the change to `~2` is one way to resolve the problem in this tutorial until the fix is released. The progress of the fix can be tracked here: [Azure/azure-functions-durable-extension#1178](https://github.com/Azure/azure-functions-durable-extension/issues/1178)
> 
> FYI @adrianstevens it'll take at least a couple of weeks to get an updated bundle that fixes this issue. Might be worth updating the Learn module to set the runtime to v2 or use the compat mode.

Thanks @anthonychu

**Comment by Adeolamorren** [comment] 2020-02-23 06:15
how do we set the runtime version to 2 instead of 3?

**Comment by MasterMartbob** [comment] 2020-02-25 15:58
I was trying to make that tutorial work https://docs.microsoft.com/en-us/azure/azure-functions/durable/quickstart-js-vscode. 
I had the error "Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead."

I applied the procedure of @cgillum first post of this issue. (Manually install the latest version of the Durable Functions)
After only needed to use "type": "durableClient" instead of "type": "orchestrationClient" in my function.json of the DurableFunctionsHttpStart.

Hope this helps. But the problem is probably more that the tutorial should be updated.

**Comment by tuanv2t** [comment] 2020-03-12 16:19
> how do we set the runtime version to 2 instead of 3?

You can click on Function Apps > Click tab "Function app settings"
<img width="938" alt="durable-fun-runtime-2" src="https://user-images.githubusercontent.com/8486393/76542680-ef038700-64b7-11ea-9ed4-c727469cb7f2.png">

**Comment by davidmrdavid** [comment] 2022-05-25 20:58
From the discussion, it appears this issue has been resolved. Marking as closed

**Closed by davidmrdavid** 2022-05-25 20:58 UTC
