### ISSUE TITLE
Sub Orchestrator only running the first sub orchestrator

### ISSUE THREAD

**Issue by KieranDaviesV** [Azure/azure-functions-durable-js#54] opened 2019-03-07 16:38 UTC
Hello,

I'm trying to run a few sub orchestrators from my main orchestrator, only my first orchestration works.

Main orchestrator

`const df = require("durable-functions");

module.exports = df.orchestrator(function* (context) {
    const input = context.df.getInput();
    const data = yield context.df.callActivity("dataStore", input.treeId);
    const nodes = data.nodes;
    const hubs = nodes.filter((node) => {
        return node.nodetype === "hub"
    });
    const sites = nodes.filter((node) => {
        // console.log(nodes);
        return node.nodetype === "site"
    });
    const results1 = yield context.df.callSubOrchestrator("CreateHubSite", { hub: hubs, table: data.table });

    const results2 = yield context.df.callSubOrchestrator("CreateSite", { sites: sites, table: data.table });

    context.log("results", results1);

});`
First sub orchestrator

`
const df = require("durable-functions");

module.exports = df.orchestrator(function* (context) {
    context.log("Starting hub site");
    const inputs = context.df.getInput();
    const hubArray = [];
    inputs.hub.forEach((hub, index) => {
        hubArray.push(context.df.callActivity("hubs", { hub: hub, table: inputs.table[0] }));
    });
    let results = yield context.df.Task.all(hubArray);

    return results;

});
`

Anything after results 1 doesn't run, not even the context.logs. I've looked through the examples and i cant see anything wrong ( I have been banging my head against this all day). Im not sure if this is a bug or I'm doing something wrong.

Thanks

**Comment by kashimiz** [comment] 2019-03-07 22:26
Hi @KieranDaviesV,

Thanks for reporting this issue. I've been able to reproduce it, and it seems to stem from not having explicitly-named sub-orchestrators, which confuses the module's history replay.

Flagging this as a bug because you should be able to call sub-orchestrators without specifying an instanceId, but in the meantime, have you tried changing your `callSubOrchestrator` calls so that `instanceId` isn't undefined?

**Comment by KieranDaviesV** [comment] 2019-03-08 11:13
Hey @kashimiz 

I've tried doing that and it seems to still be doing the same, anything after result one doesn't work. 

Im using context.df.instanceId

To get out the instance id, is this the right way?

**Comment by hanvyj** [comment] 2019-03-08 14:14
I just came to make this exact same issue.

The sub orchestrator completes, then the parent orchestrator instantly completes without performing any more logic.

I've tried modifying the call to pass in a child ID just like the tests do:

```
  const childId = context.df.instanceId + ":0";
  const enrichmentOutput: EnrichmentInputOutput = yield context.df.callSubOrchestrator(
    "socos-process-enrichment-orchestrator",
    correlationInput,
    childId
  );
  log.debug(() => `Something else!`);

  // more yeild on some other functions
```
But it results in the same behaviour. Looking at the storage, there's no errors, the parent orchestrator just instantly completes when the child orchestrator does:

![image](https://user-images.githubusercontent.com/20140222/54033039-2c4d7e80-41ab-11e9-8a2c-239f5fa17dfd.png)

No error state or anything.

**Comment by hanvyj** [comment] 2019-03-11 13:06
Ah! Updated to 1.1.4 and it seems to work fine.

**Comment by KieranDaviesV** [comment] 2019-03-11 16:08
Okay, mine now works aswell. 
I copied @hanvyj example with the childId. Thanks

**Comment by CastleArg** [comment] 2019-04-12 11:29
+1 on this issue, would be good if was in the docs as have spent many hours on this!

**Comment by CastleArg** [comment] 2019-06-05 00:33
Is there any plan to fix this any time soon?  It's a major bug and will probably drop the technology if not,

**Comment by sdoucetOctopus** [comment] 2019-06-05 14:45
> Is there any plan to fix this any time soon? It's a major bug and will probably drop the technology if not,

It was a major issue for us too. In our case, specifying an instanceid has fixed the issue...  The workaround was good enough.

```
const childId = context.df.instanceId + ":0";
const octopusDatabases = yield context.df.callSubOrchestrator('mySubOperation', undefined, childId);
```

**Comment by olivoarroba** [comment] 2019-08-16 18:58
This issue has made me bang my head for days without finding what was I doing wrong, given that Microsoft's documentation erroneously specifies that 'subOrchestrations behave just like activity functions from a caller's perspective'.
I will try specifying the instanceId, but PLEASE fix the bug!! it is very annoying...

**Comment by ConnorMcMahon** [comment] 2019-10-24 23:52
The fix for this has been merged. Should go out in next release (1.3.1 or 1.4.0, haven't decided on name yet).

**Comment by sijucm** [comment] 2021-03-23 13:07
I tried by giving a generated child_id as the instance Id, but then after certain iterations the parent just stopped working. Knowing it is a Microsoft product and because i faced many such issues with Azure, I searched internet instead of trying to debug a lot. 
Very typical of Microsoft bugs, a pure time waste. I cannot believe that these kind of immature, half baked products are allowed to be sold. If they were consumer products there would be lawsuits against Microsoft. I would like to file one for pure waste of time. No, this is not the first time-waste bugs of Microsoft that I myself faced.

**Comment by davidmrdavid** [comment] 2021-03-23 16:50
Hi @sijucm, I'm sorry to hear that. If you have a minimal reproducer handy, I can look into this issue.

**Comment by sijucm** [comment] 2021-03-24 09:03
@davidmrdavid , thanks. It is difficult to reproduce this happens under load. This is the case of an eternal orchestration with  usage of `yield context.df.continueAsNew({})`
It works for a number of iterations (very random, at times 50 at times 5) and then suddenly the orchestrator marked as complete and I do not see any clear errors. 
Note: My frustration is because I came here because I got stuck when trying to throttle the Azure functions picking up from a queue. I saw durable functions as an alternative to the queue-azure-functions approach, but now I'm stuck with the (higher level) orchestration stopping randomly. I'm still trying to make this work and this is not the first bug I experience with Azure functions.

**Comment by davidmrdavid** [comment] 2021-03-24 17:25
Hi @sijucm. Indeed, that shouldn't be happening. If you create a Bug Report here: https://github.com/Azure/azure-functions-durable-js/issues/new/choose then I can look at our internal logs to help diagnose your application. Thank you!

**Comment by karljucutan** [comment] 2021-07-01 11:55
Hello, why it's still not working for me?

I already tried:
await context.CallSubOrchestratorAsync("PolicyReinstatementOrchestrator", null, inputObject);
and concatenating string to the context.id for the CallSubOrchestratorAsync instanceId.

Code:
        public async Task RunOrchestrator(
            [OrchestrationTrigger] IDurableOrchestrationContext context)
        {
            var inputObject = context.GetInput<HttpTriggerDTO>();
            var paralleTasks = new List<Task>();

            await context.CallSubOrchestratorAsync("PolicyReinstatementOrchestrator", inputObject);
            // wont continue to the next line

**Comment by davidmrdavid** [comment] 2021-07-01 20:23
Hi @karljucutan,

Could you please open a new GitHub issue describing this problem? That will help us have a focused thread to get you unstuck as soon as possible. Thanks! It also appears, from the snippet of code you shared, that the issue you describe is for the C# SDK. If that's the case, then please create an issue in the following repo: https://github.com/Azure/azure-functions-durable-extension

**Comment by davidmrdavid** [comment] 2021-07-01 20:24
_I will also be closing this thread due to inactivity, and because new instances of this issue should be discussed in new threads. Thanks!_

**Closed by davidmrdavid** 2021-07-01 20:24 UTC
Labels: P1, bug, fix-ready
